<a href="https://colab.research.google.com/github/Divyesh-Kanagavel/GenAI_nbs/blob/master/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
# dimension zero tensor
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(5)
0
torch.Size([])


In [ ]:
# 1D tensor
vector = torch.tensor([7.0,7.0])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7., 7.])
1
torch.Size([2])


In [ ]:
# 2D tensor
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#3d tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Random tensor : in machine learning, we don't hardcode tensors like above, instead we have a random tensor, which is then updated based on an optimization function.

In [ ]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.0175, 0.0853, 0.6252, 0.1748],
        [0.0066, 0.6411, 0.2521, 0.5491],
        [0.5607, 0.9809, 0.0969, 0.2601]])


In [ ]:
random_tensor.shape, random_tensor.dtype

(torch.Size([3, 4]), torch.float32)

Zeros and ones : for some applications like masking, we may have to use tensors filled with zeros and for some other application we may need tensors full of ones. torch has functions for these.

In [ ]:
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.shape, zeros.dtype


(torch.Size([4, 4]), torch.float32)

In [ ]:
# to generate a range of numbers in a range , torch.arange() is available.
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
zero_to_ten.shape, zero_to_ten.dtype

(torch.Size([10]), torch.int64)

In [ ]:
#creating a tensor of shape same as another tensor
zeros_like_zero_to_ten = torch.zeros_like(zero_to_ten)
zeros_like_zero_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Torch datatypes : torch tensors are available in different data types depending on use cases and precision required. Some are CPU specific and others are GPU specific.if torch.cuda is found , it means the tensor is going to be used on gpu.

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Common errors while using torch tensors could be size mismatch, datatype mismatch -> torch likes tensors of same datatypes. also, one tensor could be on cpu and other could be on gpu raising issues.

In [ ]:
some_tensor = torch.rand(3, 4)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


Major operations on tensors: \
Addition \
Subtraction \
Multiplication \
Division \
Matrix multiplication \
Stacking these building blocks helps createc cool neural networks which learn how to detect objects in image, classifiy cats and dogs, write stories, detect audio and respond to them etc

In [ ]:
#Manipulating tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

in the above tensor operation, after addition, the tensor values did not get updated to 11,12,13 and remain 1,2,3. because we have not overwritten the values in the memory held by tensor

In [ ]:
tensor = tensor-10

In [ ]:
tensor

tensor([-9, -8, -7])

In [ ]:
#torch in built functions
torch.mul(tensor,10)

tensor([-90, -80, -70])

In [ ]:
torch.add(tensor,10)

tensor([1, 2, 3])

In [ ]:
# most common operation in deep learning - multiplication

tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

Built in matmul is efficient compared to doing it by hand using for loops.always prefer library matrix multiplicatios because they use optimized c code to do the lifting inside.

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 272 µs, sys: 38 µs, total: 310 µs
Wall time: 319 µs


tensor(14)

In [ ]:
%%time
value = torch.matmul(tensor, tensor)
value

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 144 µs


tensor(14)

Matrices multiplication is very common, the one common error which one could encounter is matrix shape mismatch error.the inner matrix dimension should be same for matrix multiplication to be possible.

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(tensor_A, tensor_B.T) # 3X2 multiplied with 2X3

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

torch.mm() can be used for matrix multiplication , but to be able to broadcast and do batched matrix multiplication, use torch.matmul()

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
(torch.matmul(tensor_A, tensor_B.T) == torch.mm(tensor_A, tensor_B.T)).all()


tensor(True)

In [ ]:
x = torch.arange(0, 100, 10)

In [ ]:
x

In [ ]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean : {x.type(torch.float32).mean()}")
print(f"Sum : {x.sum()}")

Minimum : 0
Maximum : 90
Mean : 45.0
Sum : 450


In [ ]:
#the same with torch method
torch.min(x), torch.max(x), torch.sum(x), torch.mean(x.type(torch.float32))

(tensor(0), tensor(90), tensor(450), tensor(45.))

type mismatch errors are quite common. they can usually be solved using type conversions.

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

In [3]:
x = torch.arange(1,8)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [4]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [5]:
z = x.view(1,7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

y = x.reshape may create a copy or view of the x's data. it depends on stride, contiguousness of data etc  z = x.view() does not create a copy. z's address is the same as x

In [6]:
x.data_ptr(), x_reshaped.data_ptr(), z.data_ptr() # in this case, reshape returns a view of the data.

(99761340747776, 99761340747776, 99761340747776)

In [7]:
z[0,0] = 5

In [8]:
z

tensor([[5, 2, 3, 4, 5, 6, 7]])

In [9]:
x # x's values is also changed since z is a view of x

tensor([5, 2, 3, 4, 5, 6, 7])

Pytorch tensors and numpy arrays

In [10]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32)

In [11]:
array = array + 1

In [12]:
array

array([2., 3., 4., 5., 6., 7., 8.])

In [13]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

pytorch tensor creates a copy of the values in numpy array, so changing the numpy array does not disturb tensor.


Computer as a machine is deterministic working on the basis of fundamental operations. So, pseudorandomness is used to generate random numbers to simulate randomness. Sometime we may wish to have same random number generated to repeat experiments and reproduce the same results.

In [14]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1591, 0.4694, 0.7207, 0.4385],
        [0.6747, 0.7121, 0.5470, 0.0463],
        [0.9167, 0.7230, 0.1673, 0.3074]])

Tensor B:
tensor([[0.7682, 0.1135, 0.7073, 0.2494],
        [0.3296, 0.6075, 0.5168, 0.3184],
        [0.8651, 0.3276, 0.4244, 0.0511]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

two tensors with random values are not the same -> they are different. \
if we want to consistenly produce the same tensors, we need to add manual_seed which can be configured.

In [22]:
import torch
import random

# # Set the random seed
RANDOM_SEED=56# try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
#torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.9531, 0.5607, 0.3535, 0.9455],
        [0.4676, 0.7281, 0.2759, 0.4734],
        [0.7383, 0.5281, 0.2217, 0.7745]])

Tensor D:
tensor([[0.4495, 0.2725, 0.4045, 0.6257],
        [0.5892, 0.5144, 0.2646, 0.3256],
        [0.4902, 0.2976, 0.0643, 0.2121]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Much of deep learning is done on GPUs due to their massive parallel computations. we will be dealing with torch.cuda() for a while now.

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.device_count()

1

In [6]:
!nvidia-smi

Sat Aug 10 13:02:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

to make pytorch make use of the GPUs or sometimes make use of CPU, we can explicity make it do so.

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
device

'cuda'


Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

In [9]:
tensor = torch.tensor([1, 2, 3])
print(tensor.device) # by default pytorch creates tensor on cpu

cpu


In [10]:
tensor_gpu = tensor.to(device)
print(tensor_gpu.device)

cuda:0


In [12]:
#let us try moving our tensor to numpy array .
arr = tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

the above conversion throws an error -> because numpy array always works on CPU. but our tensor is on gpu. to get this conversion working, we need to put our tensor on cpu first

In [13]:
arr  = tensor_gpu.cpu().numpy()

In [14]:
arr

array([1, 2, 3])

Exercises

1. Create a random tensor with shape (7, 7)

In [15]:
random_tensor = torch.rand(7,7)
print(random_tensor, random_tensor.shape)

tensor([[0.4713, 0.7335, 0.8063, 0.5008, 0.1677, 0.9801, 0.9398],
        [0.1570, 0.7886, 0.9589, 0.3007, 0.4950, 0.3068, 0.3058],
        [0.7647, 0.2875, 0.2073, 0.3925, 0.0505, 0.6207, 0.8705],
        [0.9138, 0.7786, 0.7068, 0.8084, 0.7349, 0.3003, 0.4708],
        [0.7635, 0.8991, 0.3646, 0.7438, 0.8247, 0.8482, 0.9509],
        [0.7309, 0.7603, 0.1472, 0.0780, 0.4707, 0.1795, 0.9004],
        [0.9976, 0.0759, 0.2022, 0.8178, 0.4346, 0.3229, 0.4605]]) torch.Size([7, 7])


2.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [17]:
second_random_tensor = torch.rand(1,7) #1X7 tensor
result = torch.matmul(random_tensor, second_random_tensor.T) # 7X7 X 7X1 -> transpose of second tensor
print(result, result.shape)

tensor([[2.1393],
        [1.3787],
        [1.5404],
        [1.9652],
        [2.1946],
        [1.2405],
        [1.5511]]) torch.Size([7, 1])


Set the random seed to 0 and do exercises 2 & 3 over again.

In [19]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
second_random_tensor = torch.rand(1,7) #1X7 tensor
result = torch.matmul(random_tensor, second_random_tensor.T)
print(result)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [20]:
GPU_RANDOM_SEED = 1234
torch.cuda.manual_seed(GPU_RANDOM_SEED)

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [21]:
torch.manual_seed(1234)
rand_tensor1 = torch.rand(2,3)
rand_tensor2 = torch.rand(2,3)
rand_tensor1 = rand_tensor1.to(device)
rand_tensor2 = rand_tensor2.to(device) # sending to GPU


In [24]:
rand_tensor1.device, rand_tensor2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [25]:
mul_tensor = torch.matmul(rand_tensor1, rand_tensor2.T)
print(mul_tensor.shape, mul_tensor.device)

torch.Size([2, 2]) cuda:0


Find the maximum and minimum values of the output of 7.

In [27]:
torch.max(mul_tensor), torch.min(mul_tensor)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

Find the maximum and minimum index values of the output of 7.

In [28]:
torch.argmax(mul_tensor), torch.argmin(mul_tensor)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [29]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
rand_tensor = torch.rand(1,1,1,10)
new_tensor = rand_tensor.reshape(10,)
print(rand_tensor, rand_tensor.shape)
print(new_tensor, new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


EXTRA-CURRICULUM
Spend 1-hour going through the PyTorch basics tutorial (I'd recommend the Quickstart and Tensors sections).

In [30]:
#Quickstart section
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

PyTorch has two primitives to work with data: torch.utils.data.DataLoader and torch.utils.data.Dataset. Dataset stores the samples and their corresponding labels, and DataLoader wraps an iterable around the Dataset.

The torchvision.datasets module contains Dataset objects for many real-world vision data like CIFAR, COCO (full list here). In this tutorial, we use the FashionMNIST dataset. Every TorchVision Dataset includes two arguments: transform and target_transform to modify the samples and labels respectively.

In [31]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

100%|██████████| 26421880/26421880 [00:01<00:00, 14563862.62it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 211269.21it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3921241.33it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 5352572.38it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [32]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [33]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

In [34]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [35]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [36]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train() # converting model to training mode , weight updation allowed, batch_norm computations
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [37]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval() # model in eval model
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [38]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.296786  [   64/60000]
loss: 2.283614  [ 6464/60000]
loss: 2.261756  [12864/60000]
loss: 2.260089  [19264/60000]
loss: 2.245416  [25664/60000]
loss: 2.215900  [32064/60000]
loss: 2.223479  [38464/60000]
loss: 2.184617  [44864/60000]
loss: 2.184131  [51264/60000]
loss: 2.164225  [57664/60000]
Test Error: 
 Accuracy: 45.9%, Avg loss: 2.146407 

Epoch 2
-------------------------------
loss: 2.153422  [   64/60000]
loss: 2.139457  [ 6464/60000]
loss: 2.082509  [12864/60000]
loss: 2.108061  [19264/60000]
loss: 2.051344  [25664/60000]
loss: 1.991234  [32064/60000]
loss: 2.028909  [38464/60000]
loss: 1.938366  [44864/60000]
loss: 1.952656  [51264/60000]
loss: 1.895749  [57664/60000]
Test Error: 
 Accuracy: 51.4%, Avg loss: 1.878337 

Epoch 3
-------------------------------
loss: 1.910406  [   64/60000]
loss: 1.871939  [ 6464/60000]
loss: 1.763350  [12864/60000]
loss: 1.817200  [19264/60000]
loss: 1.694584  [25664/60000]
loss: 1.653580  [32064/600